### ISSUE TITLE
symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0

### ISSUE THREAD

**Issue by quienn** [blahgeek/emacs-appimage#1]
Every time I try to run the AppImage (tried both with 29.1 and master/daily build) this is the output I get:

```
/tmp/.mount_Emacs-BlKoMm/bin/emacs: symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0
```

Currently running Arch Linux.

```
$ pacman -Q libtiff libjpeg-turbo 
libtiff 4.6.0-2
libjpeg-turbo 3.0.1-1
```

**Comment by blahgeek** [comment]
Hi,

Could you do the following steps and provide the logs

- Extract the appimage (`./Emacs.appimage --appimage-extract; cd squashfs-root`), run lddtree: `lddtree ./bin/emacs`
- Run emacs with LD debug: `env LD_DEBUG=all ./Emacs.appimage`

thanks

**Comment by quienn** [comment]
Just as I thought, there was a problem with my Arch installation. I can't reproduce this on a fresh install. 😁 Might aswell just close this issue.

**Comment by endiexz** [comment]
I also came cross this problem when I installed BitComet as .AppImage file type.
[endiexz@EN Downloads]$ sudo ./BitComet-2.5.1-x86_64.AppImage
/tmp/.mount_BitCom3vAl1Z/usr/bin/BitComet: symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0

**Comment by quienn** [comment]
Fresh Arch installation, this happened yet again! But I've seen there's a bunch of similar errors out there. 🤔

https://forum.manjaro.org/t/cant-start-onlyoffice-appimage/148332
https://github.com/ente-io/ente/issues/472
https://github.com/ente-io/ente/issues/1978

**Comment by blahgeek** [comment]
@quienn thanks for the report. I have identified and fixed the issue (but unfortunately had to drop tiff support). Please download the newest version from the release page to see if it fixes the issue for you.

**Comment by quienn** [comment]
Yes it does fix it! All variants now work perfectly fine in Arch.
