### ISSUE TITLE
libmpc.so.3 missing

### ISSUE THREAD

**Issue by SebastianMpl** [blahgeek/emacs-appimage#2]
Hi there,
Thank you for your emacs-nox build.
Under Archbang when I run the image I get
error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
When I install it (only 1 lib 0.17 Mb) the image runs fine.
When I place the so file and its links to lib folder in extracted appimage i still get the above message even that lddtree sees it:
libmpc.so.3 => /home/seba/Pobrane/squashfs-root/lib/libmpc.so.3

Could you please add libmpc.so.3 to nox build?

Thank you

**Comment by SebastianMpl** [comment]
Sorry, I had to modify AppRun a little. Works fine

**Comment by blahgeek** [comment]
Thanks for your report. I can confirm this issue and have fixed it in the latest release. Please try it to see if it fixes your issue.
