### ISSUE TITLE
Request to include non-nativecomp version

### ISSUE THREAD

**Issue by paniash** [blahgeek/emacs-appimage#4]
Hi! 

Thanks a lot for this wonderful appimage. It's been a boon on my office pc where we have restrictions on installing software through the official repos.

I was wondering if you could also include non-nativecomp versions for the appimage. I ask this because of a known issue with `evil` where nativecomp gives out an error. Also, eln-cache gets generated and each time I wish to install a package, I get the "maximum buffer size exceeded" error till I manually delete the `eln-cache` directory from my `.emacs.d/`.

**Comment by blahgeek** [comment]
Also, if you really want to disable native-comp, does `(setq native-comp-jit-compilation nil)` work?

**Comment by paniash** [comment]
> Hello,
> 
> I'm glad that this is helpful for you.
> 
> About the non-native-comp versions: if it's really the case that there are known issues about native-comp, I would agree to include that in release. However, I'm curious and doubtful if the issues are really about native-comp, since personally I've been using native-comp versions with evil and lots of other packages for a long time without any issues. Can you provide more details about your issue? Thanks

Thanks for your reply. It's a good question because I use the native-comp version on my personal laptop and I've had no issues but for some reason the appimage version on my office computer has this problem, especially the "maximum buffer size exceeded" error when installing any new package.

I'll test out a few more things and see if native-comp is really the issue or if it's something else, even though I use the same `init.el` on both my machines.

Do you think it might have to do with the version of emacs? The appimage seems to be the bleeding edge one with v30 release, which to my knowledge has native-comp activated by default. My personal laptop is running the stable release version 29.4

**Comment by blahgeek** [comment]
You can try the appimage of version 29.4 with native-comp enabled [here](https://github.com/blahgeek/emacs-appimage/releases/tag/github-action-build-9737223047)

**Comment by paniash** [comment]
> You can try the appimage of version 29.4 with native-comp enabled [here](https://github.com/blahgeek/emacs-appimage/releases/tag/github-action-build-9737223047)

Thanks! This seems to have fixed the problem for now. :)
