### ISSUE TITLE
How to compile init.el and plug-ins to appimages

### ISSUE THREAD

**Issue by mikuyo** [blahgeek/emacs-appimage#6]
How to compile init.el and plug-ins to appimages,This works right out of the box.
Can it be achieved, or do you have any ideas, thank you.

**Comment by blahgeek** [comment]
I haven't tried it myself, but it's definitely possible. I think you can make use of "site-wide init files" and put them in "../share/emacs/$VERSION/site-lisp". You can modify postprocess.py to install additional files to the directory.

Some links:

- https://www.gnu.org/software/emacs/manual/html_node/eintr/Site_002dwide-Init.html
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Search.html
- https://github.com/blahgeek/emacs-appimage/blob/f9f8c19032811c054914c1e07ef9c9423e92615d/scripts/AppRun#L7C38-L7C63
- https://github.com/blahgeek/emacs-appimage/blob/master/scripts/postprocess.py

**Comment by mikuyo** [comment]
Tanks,this's working.
